[package]
name = "driftwm-settings"
version = "0.5.0"
edition = "2024"

[dependencies]
iced = { version = "0.13", features = ["tokio", "advanced", "svg"] }
serde = { version = "1.0", features = ["derive"] }
toml_edit = { version = "0.22", features = ["serde"] }
toml = "0.8"
dirs = "6.0"
anyhow = "1"

[profile.dev]
debug = 0

[profile.test]
debug = 0
